### ISSUE TITLE
Example template office perspective can only rotate/scroll to the left, and can't go back or go right

### ISSUE THREAD

**Issue by BarykadyDrogowe12** [Oplexitie/Cupcakes-Framework#2] opened 2023-11-14 20:28 UTC
Fresh out of the box imported project
Godot v4.1.3 
OpenGL API 3.3.0 
Raden RX 570 Series

Display:
3840x2160

It wasn't a build, it was run inside the editor for tests, no changes were made to the office scroll script or main structure

**Comment by BarykadyDrogowe12** [comment] 2023-11-14 20:28
In short: I can only look left with my mouse, and can't look right at all

**Comment by Oplexitie** [comment] 2023-11-15 10:24
@BarykadyDrogowe12 Hello, thank you for bringing this to my attention. After looking into the issue, the problem seems to be exclusive to Godot 4 and caused by how the _office_scroll.gd_ script retrieves the viewport size. Leading to issues with anything but 1920x1080 displays. So in your case, your 4K display triggered the issue.

I'll push a fix out as soon as I can confirm that it actually works.

**Comment by Oplexitie** [comment] 2023-11-15 21:13
@BarykadyDrogowe12 The fix is now live on Github ! It should be available in the Godot Asset Library soon (in version 1.3.2).
And since I've tested the fix on a 2K Ultra Wide monitor, and can confirm that the scrolling now works, I'll close the issue.

**Closed as completed by Oplexitie** 2023-11-15 21:13 UTC
